---
- name: Install Jenkins
  hosts: web
  become: yes
  roles:
    - java-21
    - git
    - jenkins

- name: Install Development Tools
  hosts: web
  become: yes
  roles:
    - java-11
    - git
    - docker
    - sonarqube
    - oc